### ISSUE TITLE
Add independent expenditure data as a standalone download

### ISSUE THREAD

**Issue by hancush** [datamade/nmid#211]
Make independent expenditure data available as a standalone download, likely something similar to [Lobbyist Disclosures](https://moneytrailnm.com/financial-disclosures/), but confirm with Marjorie.

Depends on https://github.com/datamade/nmid-scrapers/issues/27

**Comment by antidipyramid** [comment]
After uploading independent expenditure data as an excel file to S3, is this just a matter of adding some text to the staging/prod site databases?

**Comment by hancush** [comment]
Email Marjorie with the link and ask how she would like it added to the site.

**Comment by antidipyramid** [comment]
@hancush Marjorie would like this to be added to the current data download page. All of the other downloads on this page pull from the Django db-- we've just got an excel file for independent expenditures. 

Just want to make sure that we're not expected to do the same for these independent expenditures. Otherwise, I'll add link to the file in S3 to [this page](https://github.com/datamade/openness-project-nmid/blob/5bf35c07278cf069055c32614bb7e752f2ac5b8a/pages/templates/downloads.html).
